### ISSUE TITLE
Change a line for JRE7 compatibility

### ISSUE THREAD

**Issue by MrStahlfelge** [inkytonik/kiama#28]
This line makes the lib incompatible with Android <= 7:

https://github.com/inkytonik/kiama/blob/96625397e7889b569981f1301ed2a035d71c7e7d/core/src/main/scala/org/bitbucket/inkytonik/kiama/rewriting/Rewriter.scala#L386

Could you change it to `ctor.getParameterTypes().length` for Java 7 compatibility?

**Comment by inkytonik** [comment]
Thanks for the suggestion. Your suggested change seems to be fine. It will be in Kiama 2.5.0 which I plan to release in the near future.

**Comment by inkytonik** [comment]
Fixed by 7b4dca88a0fd6ee5855e2cb16ed689a34a0194c8.

**Comment by MrStahlfelge** [comment]
Thanks! Is there a snapshot version published? I would love to check if there are any other problems on Android 7 or if we are good to go with the new version.

**Comment by inkytonik** [comment]
I've just published 2.5.0-SNAPSHOT for Scala 2.12, 2.13 and 3. If you spot any problems, please let me know via new issues and I'll see if fixes can make it into 2.5.0. Thanks for your help.

**Comment by MrStahlfelge** [comment]
Thank you! Sorry for the extra effort, Scala 2.11 is the last one working with Java 7 so that is the version I have to use.

**Comment by inkytonik** [comment]
No worries. The 2.11 one is there now. FWIW, the reason it wasn't is that I was still resolving some library issues since some of the modern versions of things like ScalaTest and ScalaCheck are not published for 2.11 any more.

**Comment by MrStahlfelge** [comment]
Works now!

**Comment by inkytonik** [comment]
Great! Thanks for letting me know.
