### ISSUE TITLE
IntelliJ IDEA complains about type mismatch on `rule[Exp] { ... }` if partial function return type differs

### ISSUE THREAD

**Issue by aleksandr-vin** [inkytonik/kiama#6]
It is not a problem for scalac or sbt build but while working in IntelliJ IDEA, she complains with messages of this sort:

> Type mismatch. Required: Exp ===> Exp, found: PartialFunction[Exp, Num]

Version info:

Kiama commit 85df331e

IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Non-Bundled Plugins: org.intellij.scala

**Comment by aleksandr-vin** [comment]
@inkytonik thanks for fast reaction. What are the plans for release?

**Comment by inkytonik** [comment]
No problem. Thanks for the report. I would like to do a release in the next two weeks and that should be possible. There are a few smallish things already done that it would be nice to get out in 2.4.0. Do you have anything else that would be good to include?

**Comment by aleksandr-vin** [comment]
No, nothing for now. Will be waiting for 2.4.0. Thanks

**Comment by inkytonik** [comment]
Ok, thanks. I'll try to get it out soon.
